-- 코드를 입력하세요
SELECT INFO.INGREDIENT_TYPE, SUM(FIRST.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS FIRST
INNER JOIN ICECREAM_INFO AS INFO ON FIRST.FLAVOR = INFO.FLAVOR
GROUP BY INFO.INGREDIENT_TYPE 
ORDER BY TOTAL_ORDER ASC;