-- CTE
WITH JAN_SALES AS (
    SELECT BOOK_ID, 
    SUM(SALES) AS TOTAL_SALES
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID
)

SELECT CATEGORY, 
    SUM(TOTAL_SALES) AS TOTAL_SALES
FROM JAN_SALES AS J
JOIN BOOK AS B
ON B.BOOK_ID = J.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY;